name: killi-pipeline
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - scipy
  - scikit-image
  - simpleitk
  - statsmodels
  - zarr
  - dask
  - dask-core
  - tqdm
  - filelock
  - numcodecs
  - glob2
  - pip
  - pip:
      - bioio
      - bioio-ome-zarr
      - bioio-czi
      - cellpose
      - ultrack
